#!/bin/sh
update-alternatives --install /usr/lib/tensorflow tensorflow /usr/lib/tensorflow1.11-cpu/ 100

if [ -d /usr/lib/tensorflow1.11-cpu/include/tensorflow/absl ]; then
    ln -s /usr/lib/tensorflow1.11-cpu/include/tensorflow/tensorflow/contrib/makefile/downloads/absl/absl \
        /usr/lib/tensorflow1.11-cpu/include/tensorflow/
fi

ldconfig